pythonbrew-install script accept Python-2.7

diff --git a/pythonbrew-install b/pythonbrew-install
--- a/pythonbrew-install
+++ b/pythonbrew-install
@@ -45,13 +45,13 @@ for PYTHON in $PYTHONS ; do
 	PYTHON_VERSION=${PYTHON_VERSION/"Python "/""}
 	PYTHON_VERSION_S=`echo $PYTHON_VERSION | sed -e "s/\(^[[:digit:]]\{1,\}.[[:digit:]]\{1,\}\).*/\1/"`
 	
-	if [[ $PYTHON_VERSION_S = "2.4" ]] || [[ $PYTHON_VERSION_S = "2.5" ]] || [[ $PYTHON_VERSION_S = "2.6" ]] ; then
+	if [[ $PYTHON_VERSION_S = "2.4" ]] || [[ $PYTHON_VERSION_S = "2.5" ]] || [[ $PYTHON_VERSION_S = "2.6" ]] || [[ $PYTHON_VERSION_S = "2.7" ]] ; then
 		PYTHON_FOUND='1'
 		break
 	fi
 done
 if [[ $PYTHON_FOUND != '1' ]] ; then
-    echo "pythonbrew required Python (2.4, 2.5 or 2.6)."
+    echo "pythonbrew required Python (2.4, 2.5, 2.6 or 2.7)."
     #TODO Installing python.
     exit
 fi
@@ -63,6 +63,10 @@ fi
 PATH_DISTS="$ROOT/dists"
 
 STABLE_VERSION=`curl -skL https://github.com/utahta/pythonbrew/raw/master/stable-version.txt`
+if [[ $STABLE_VERSION = "" ]] ; then
+    echo 'Could not get stable-version of pythonbrew.'
+    exit 1
+fi
 TEMP_FILE="pythonbrew-$STABLE_VERSION"
 TEMP_TARBALL="$TEMP_FILE.tar.gz"
 DOWNLOAD_URL="http://pypi.python.org/packages/source/p/pythonbrew/$TEMP_TARBALL"
